# Generated by Django 4.1.4 on 2022-12-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_data_criacao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='data_criacao_usuario',
            field=models.DateField(auto_now_add=True),
        ),
    ]
