# Generated by Django 4.1.4 on 2022-12-28 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliarColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliado', models.BooleanField(default=False)),
                ('calculo', models.FloatField(default=0.0)),
                ('data_avaliacao_colaborador', models.DateField(blank=True, null=True)),
                ('liberar_avaliacao', models.BooleanField(default=False)),
                ('avaliacao_chefes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_chefes', to='avaliacao.avaliacao')),
                ('avaliacao_colaboradores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_colaboradores', to='avaliacao.avaliacao')),
                ('criterio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaliacao.criterio')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Avaliar Colaboradores',
            },
        ),
    ]
