# Generated by Django 4.1.4 on 2022-12-28 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
        ('avaliar_colaborador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliarcolaborador',
            name='avaliacao_chefes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_chefe', to='avaliacao.avaliacao'),
        ),
        migrations.AlterField(
            model_name='avaliarcolaborador',
            name='avaliacao_colaboradores',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_colaboradore', to='avaliacao.avaliacao'),
        ),
    ]
