# Generated by Django 4.1.4 on 2022-12-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliar_colaborador', '0002_remove_avaliarcolaborador_avaliacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliarcolaborador',
            name='calculo',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='avaliarcolaborador',
            name='data_avaliacao_usuario',
            field=models.DateField(blank=True, null=True),
        ),
    ]
