# Generated by Django 4.1.5 on 2023-01-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
        ('avaliar_colaborador', '0003_alter_avaliarcolaborador_avaliacao_chefes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliarcolaborador',
            name='avaliacao_chefes',
        ),
        migrations.RemoveField(
            model_name='avaliarcolaborador',
            name='avaliacao_colaboradores',
        ),
        migrations.AddField(
            model_name='avaliarcolaborador',
            name='avaliacao_chefes',
            field=models.ManyToManyField(blank=True, related_name='avaliacao_chefes', to='avaliacao.avaliacao'),
        ),
        migrations.AddField(
            model_name='avaliarcolaborador',
            name='avaliacao_colaboradores',
            field=models.ManyToManyField(blank=True, related_name='avaliacao_colaboradores', to='avaliacao.avaliacao'),
        ),
    ]
