# Generated by Django 4.1.4 on 2022-12-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_avaliacao_visivel'),
        ('avaliar_colaborador', '0003_avaliarcolaborador_calculo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliarcolaborador',
            name='avaliacao_chefes',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('visivel', 'chefes'), ('visivel', 'todos'), _connector='OR'), related_name='meritos_chefes', to='avaliacao.avaliacao'),
        ),
        migrations.AddField(
            model_name='avaliarcolaborador',
            name='avaliacao_colaboradores',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('visivel', 'colaboradores'), ('visivel', 'todos'), _connector='OR'), related_name='meritos_colaboradores', to='avaliacao.avaliacao'),
        ),
    ]
