# Generated by Django 4.1.5 on 2023-01-02 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avaliacao', '0002_alter_criterio_options_alter_avaliacao_avaliacao_and_more'),
        ('avaliar_colaborador', '0004_remove_avaliarcolaborador_avaliacao_chefes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliarcolaborador',
            name='avaliacao_chefes',
            field=models.ManyToManyField(blank=True, related_name='avaliacao_chefes', to='avaliacao.avaliacao', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='avaliarcolaborador',
            name='avaliacao_colaboradores',
            field=models.ManyToManyField(blank=True, related_name='avaliacao_colaboradores', to='avaliacao.avaliacao', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='avaliarcolaborador',
            name='calculo',
            field=models.FloatField(default=0.0, verbose_name='Cálculo'),
        ),
        migrations.AlterField(
            model_name='avaliarcolaborador',
            name='criterio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_colaboradores', to='avaliacao.criterio', verbose_name='Critério'),
        ),
        migrations.AlterField(
            model_name='avaliarcolaborador',
            name='data_avaliacao_colaborador',
            field=models.DateField(blank=True, null=True, verbose_name='Data da última avaliação'),
        ),
        migrations.AlterField(
            model_name='avaliarcolaborador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
