# Generated by Django 4.1.4 on 2022-12-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_avaliacao_visivel'),
        ('avaliar_colaborador', '0004_avaliarcolaborador_avaliacao_chefes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliarcolaborador',
            name='avaliacao_chefes',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('visivel', 'chefes'), ('visivel', 'todos'), _connector='OR'), related_name='avaliacao_chefes', to='avaliacao.avaliacao'),
        ),
        migrations.AlterField(
            model_name='avaliarcolaborador',
            name='avaliacao_colaboradores',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('visivel', 'colaboradores'), ('visivel', 'todos'), _connector='OR'), related_name='avaliacao_colaboradores', to='avaliacao.avaliacao'),
        ),
    ]
