# Generated by Django 4.1.5 on 2023-01-04 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_alter_criterio_options_alter_avaliacao_avaliacao_and_more'),
        ('avaliar_colaborador', '0005_alter_avaliarcolaborador_avaliacao_chefes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliarcolaborador',
            name='avaliacao_chefes',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('visivel', 'chefes'), ('visivel', 'todos'), _connector='OR'), related_name='avaliacao_chefes', to='avaliacao.avaliacao', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='avaliarcolaborador',
            name='avaliacao_colaboradores',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('visivel', 'colaboradores'), ('visivel', 'todos'), _connector='OR'), related_name='avaliacao_colaboradores', to='avaliacao.avaliacao', verbose_name=''),
        ),
    ]
