# Generated by Django 4.1.4 on 2022-12-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliar_colaborador', '0005_alter_avaliarcolaborador_avaliacao_chefes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliarcolaborador',
            name='liberar_avaliacao',
            field=models.BooleanField(default=False),
        ),
    ]
