# Generated by Django 4.1.4 on 2022-12-26 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0007_remove_avaliacao_visivel_criterio_visivel'),
        ('avaliar_colaborador', '0006_avaliarcolaborador_liberar_avaliacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliarcolaborador',
            old_name='data_avaliacao_usuario',
            new_name='data_avaliacao_colaborador',
        ),
        migrations.AddField(
            model_name='avaliarcolaborador',
            name='criterio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='avaliacao.criterio'),
            preserve_default=False,
        ),
    ]
