# Generated by Django 4.1.4 on 2022-12-26 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0007_remove_avaliacao_visivel_criterio_visivel'),
        ('avaliar_colaborador', '0007_rename_data_avaliacao_usuario_avaliarcolaborador_data_avaliacao_colaborador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliarcolaborador',
            name='criterio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaliacao.criterio'),
        ),
    ]
