# Generated by Django 4.1.4 on 2022-12-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliar_colaborador', '0008_alter_avaliarcolaborador_criterio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliarcolaborador',
            options={'verbose_name_plural': 'Avaliar Colaboradores'},
        ),
        migrations.RemoveField(
            model_name='avaliarcolaborador',
            name='criterio',
        ),
    ]
