# Generated by Django 4.1.4 on 2022-12-26 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0007_remove_avaliacao_visivel_criterio_visivel'),
        ('avaliar_colaborador', '0009_alter_avaliarcolaborador_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliarcolaborador',
            name='criterio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avaliacao.criterio'),
        ),
        migrations.AlterField(
            model_name='avaliarcolaborador',
            name='avaliacao_chefes',
            field=models.ManyToManyField(blank=True, related_name='avaliacao_chefes', to='avaliacao.avaliacao'),
        ),
        migrations.AlterField(
            model_name='avaliarcolaborador',
            name='avaliacao_colaboradores',
            field=models.ManyToManyField(blank=True, related_name='avaliacao_colaboradores', to='avaliacao.avaliacao'),
        ),
    ]
