# Generated by Django 4.1.5 on 2023-01-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diretoria_e_gerencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gerencia',
            name='gerencia',
            field=models.CharField(max_length=100, verbose_name='Gerência'),
        ),
    ]
