# Generated by Django 4.1.4 on 2022-12-15 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avaliacao_otima', models.TextField()),
                ('avaliacao_boa', models.TextField()),
                ('avaliacao_regular', models.TextField()),
                ('avaliacao_insuficiente', models.TextField()),
                ('categoria_avaliacao', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='avaliacao.categoria')),
            ],
            options={
                'verbose_name': 'Avaliação',
                'verbose_name_plural': 'Avaliações',
            },
        ),
    ]
