# Generated by Django 4.1.5 on 2023-01-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_alter_criterio_options_alter_avaliacao_avaliacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacao',
            name='visivel',
            field=models.CharField(choices=[('chefes', 'Chefes'), ('colaboradores', 'Colaboradores'), ('todos', 'Todos')], default=1, max_length=20, verbose_name='Visibilidade'),
            preserve_default=False,
        ),
    ]
