# Generated by Django 4.1.4 on 2022-12-20 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0002_avaliacao_visivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criterio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterio', models.CharField(max_length=50, unique=True)),
                ('definicao', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='avaliacao',
            old_name='avaliacao_boa',
            new_name='avaliacao',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='avaliacao_insuficiente',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='avaliacao_otima',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='avaliacao_regular',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='categoria_avaliacao',
        ),
        migrations.RemoveField(
            model_name='avaliacao',
            name='visivel',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='escala',
            field=models.CharField(choices=[('o', 'Otimo'), ('b', 'Bom'), ('r', 'Ruim'), ('i', 'Insuficiente')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='criterio_avaliacao',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='avaliacao.criterio'),
            preserve_default=False,
        ),
    ]
