# Generated by Django 4.1.4 on 2022-12-22 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0003_criterio_rename_avaliacao_boa_avaliacao_avaliacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliacao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='criterio_avaliacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.criterio'),
        ),
    ]
