# Generated by Django 4.1.4 on 2022-12-22 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0004_alter_avaliacao_avaliacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='avaliacao',
            field=models.TextField(),
        ),
    ]
