# Generated by Django 4.1.4 on 2022-12-22 10:22

import avaliar_usuario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliar_usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arquivo',
            name='file',
            field=models.FileField(blank=True, upload_to=avaliar_usuario.models.folder_upload),
        ),
    ]
