# Generated by Django 4.1.4 on 2022-12-16 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avaliar_usuario', '0002_avaliarusuario_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliarusuario',
            name='slug',
        ),
    ]
