# Generated by Django 4.1.5 on 2023-01-02 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('desempenho', '0008_alter_fatordesempenhodemerito_visivel_and_more'),
        ('avaliar_usuario', '0003_alter_arquivo_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avaliarusuario',
            options={'verbose_name': 'Avaliar Usuário'},
        ),
        migrations.AlterField(
            model_name='avaliarusuario',
            name='calculo',
            field=models.FloatField(default=0.0, verbose_name='Cálculo'),
        ),
        migrations.AlterField(
            model_name='avaliarusuario',
            name='data_avaliacao_usuario',
            field=models.DateField(blank=True, null=True, verbose_name='Data da última avaliação'),
        ),
        migrations.AlterField(
            model_name='avaliarusuario',
            name='demeritos_chefes',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('visivel', 'chefes'), ('visivel', 'todos'), _connector='OR'), related_name='demeritos_chefes', to='desempenho.fatordesempenhodemerito', verbose_name='Deméritos'),
        ),
        migrations.AlterField(
            model_name='avaliarusuario',
            name='demeritos_colaboradores',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('visivel', 'colaboradores'), ('visivel', 'todos'), _connector='OR'), related_name='demeritos_colaboradores', to='desempenho.fatordesempenhodemerito', verbose_name='Deméritos'),
        ),
        migrations.AlterField(
            model_name='avaliarusuario',
            name='meritos_chefes',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('visivel', 'chefes'), ('visivel', 'todos'), _connector='OR'), related_name='meritos_chefes', to='desempenho.fatordesempenhomerito', verbose_name='Méritos'),
        ),
        migrations.AlterField(
            model_name='avaliarusuario',
            name='meritos_colaboradores',
            field=models.ManyToManyField(blank=True, limit_choices_to=models.Q(('visivel', 'colaboradores'), ('visivel', 'todos'), _connector='OR'), related_name='meritos_colaboradores', to='desempenho.fatordesempenhomerito', verbose_name='Méritos'),
        ),
        migrations.AlterField(
            model_name='avaliarusuario',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nome', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
