# Generated by Django 4.1.5 on 2023-01-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdicionarEdital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edital', models.CharField(max_length=150, unique=True, verbose_name='Nome Edital')),
                ('data_inicio', models.DateField(blank=True, null=True, verbose_name='Data de início')),
                ('data_termino', models.DateField(blank=True, null=True, verbose_name='Data de término')),
                ('permitido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Edital',
                'verbose_name_plural': 'Editais',
            },
        ),
    ]
