# Generated by Django 4.1.5 on 2023-01-03 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicionaredital',
            name='edital',
            field=models.CharField(max_length=150, unique=True, verbose_name='Nome do Edital'),
        ),
    ]
