# Generated by Django 4.1.5 on 2023-01-03 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0002_alter_adicionaredital_edital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adicionaredital',
            name='permitido',
        ),
        migrations.AddField(
            model_name='adicionaredital',
            name='andamento',
            field=models.BooleanField(default=False, verbose_name='Em andamento'),
        ),
    ]
