# Generated by Django 4.1.5 on 2023-01-03 11:23

from django.db import migrations, models
import django.db.models.deletion
import edital.models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0003_remove_adicionaredital_permitido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=edital.models.folder_upload)),
                ('edital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edital.adicionaredital')),
            ],
        ),
    ]
