# Generated by Django 4.1.5 on 2023-01-03 11:26

from django.db import migrations, models
import edital.models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0004_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adicionaredital',
            name='file',
            field=models.FileField(default=1, upload_to=edital.models.folder_upload),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Arquivo',
        ),
    ]
