# Generated by Django 4.1.5 on 2023-01-03 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0005_adicionaredital_file_delete_arquivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adicionaredital',
            old_name='file',
            new_name='arquivo',
        ),
    ]
