# Generated by Django 4.1.5 on 2023-01-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0006_rename_file_adicionaredital_arquivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adicionaredital',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='adicionaredital',
            name='data_termino',
        ),
        migrations.AddField(
            model_name='adicionaredital',
            name='periodo',
            field=models.DurationField(blank=True, null=True, verbose_name='Período'),
        ),
    ]
