# Generated by Django 4.1.5 on 2023-01-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0007_remove_adicionaredital_data_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adicionaredital',
            name='periodo',
        ),
        migrations.AddField(
            model_name='adicionaredital',
            name='data_inicio',
            field=models.DurationField(blank=True, null=True, verbose_name='Data de início'),
        ),
        migrations.AddField(
            model_name='adicionaredital',
            name='data_termino',
            field=models.DateField(blank=True, null=True, verbose_name='Data de término'),
        ),
    ]
