# Generated by Django 4.1.5 on 2023-01-03 13:26

from django.db import migrations, models
import edital.models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0008_remove_adicionaredital_periodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicionaredital',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to=edital.models.folder_upload),
        ),
        migrations.AlterField(
            model_name='adicionaredital',
            name='data_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Data de início'),
        ),
        migrations.AlterField(
            model_name='adicionaredital',
            name='edital',
            field=models.CharField(max_length=150, verbose_name='Nome do Edital'),
        ),
    ]
