# Generated by Django 4.1.5 on 2023-01-03 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edital', '0010_alter_adicionaredital_edital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adicionaredital',
            name='edital',
            field=models.CharField(max_length=150, verbose_name='Nome do Edital'),
        ),
    ]
