# Generated by Django 4.1.4 on 2022-12-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desempenho', '0003_fatordesempenhodemerito_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatordesempenhodemerito',
            name='tipo',
            field=models.CharField(choices=[('chefe', 'Chefe'), ('colaborador', 'Colaborador'), ('todos', 'Todos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fatordesempenhomerito',
            name='tipo',
            field=models.CharField(choices=[('chefe', 'Chefe'), ('colaborador', 'Colaborador'), ('todos', 'Todos')], max_length=20),
        ),
    ]
