# Generated by Django 4.1.4 on 2022-12-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desempenho', '0004_alter_fatordesempenhodemerito_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fatordesempenhodemerito',
            options={'verbose_name': 'Demérito'},
        ),
        migrations.AlterModelOptions(
            name='fatordesempenhomerito',
            options={'verbose_name': 'Mérito'},
        ),
    ]
