# Generated by Django 4.1.4 on 2022-12-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desempenho', '0005_alter_fatordesempenhodemerito_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fatordesempenhodemerito',
            options={'verbose_name': 'Fator Demeritório'},
        ),
        migrations.AlterModelOptions(
            name='fatordesempenhomerito',
            options={'verbose_name': 'Fator Meritório'},
        ),
        migrations.AlterField(
            model_name='fatordesempenhodemerito',
            name='tipo',
            field=models.CharField(choices=[('chefes', 'Chefes'), ('colaboradores', 'Colaboradores'), ('todos', 'Todos')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fatordesempenhomerito',
            name='tipo',
            field=models.CharField(choices=[('chefes', 'Chefes'), ('colaboradores', 'Colaboradores'), ('todos', 'Todos')], max_length=20),
        ),
    ]
