# Generated by Django 4.1.4 on 2022-12-19 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desempenho', '0006_alter_fatordesempenhodemerito_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fatordesempenhodemerito',
            options={'verbose_name': 'Fator Demeritório', 'verbose_name_plural': 'Fatores Demeritórios'},
        ),
        migrations.AlterModelOptions(
            name='fatordesempenhomerito',
            options={'verbose_name': 'Fator Meritório', 'verbose_name_plural': 'Fatores Meritórios'},
        ),
        migrations.RenameField(
            model_name='fatordesempenhodemerito',
            old_name='tipo',
            new_name='visivel',
        ),
        migrations.RenameField(
            model_name='fatordesempenhomerito',
            old_name='tipo',
            new_name='visivel',
        ),
    ]
