# Generated by Django 4.1.5 on 2023-01-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desempenho', '0007_alter_fatordesempenhodemerito_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatordesempenhodemerito',
            name='visivel',
            field=models.CharField(choices=[('chefes', 'Chefes'), ('colaboradores', 'Colaboradores'), ('todos', 'Todos')], max_length=20, verbose_name='Visibilidade'),
        ),
        migrations.AlterField(
            model_name='fatordesempenhomerito',
            name='visivel',
            field=models.CharField(choices=[('chefes', 'Chefes'), ('colaboradores', 'Colaboradores'), ('todos', 'Todos')], max_length=20, verbose_name='Visibilidade'),
        ),
    ]
